name = "p2pchat"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "p2pchat-storage"
id = "9994381c5426453890bf7e0eac2e965f"

[env.production]
compatibility_date = "2024-01-01"

[[env.production.kv_namespaces]]
binding = "p2pchat-storage"
id = "9994381c5426453890bf7e0eac2e965f"
